project_4/project_crud/app_crud/urls.py
from django.urls import path

from app_crud.views import person_list, person_detail, person_new, person_edit, person_delete

urlpatterns = [
    path('', person_list, name='person_list'),
    path('person/<int:pk>/', person_detail, name='person_detail'),
    path('person/new', person_new, name='person_new'),
    path('person/<int:pk>/edit/', person_edit, name='person_edit'),
    path('person/<int:pk>/delete', person_delete, name='person_delete')
]

project_4/project_crud/project_crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('app_crud.urls'))
]

project_4/project_crud/app_crud/models.py
from django.db import models


# Create your models here.
class Hobby(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Person(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    ]

    COUNTRY_CHOICES = [
        ('bd', 'Bangladesh'),
        ('jp', 'Japan'),
        ('us', 'USA')
    ]
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    hobbies = models.ManyToManyField(Hobby, blank=True)
    country = models.CharField(max_length=2, choices=COUNTRY_CHOICES)
    comments = models.TextField()
    birth_date = models.DateField()


def __str__(self):
    return self.name

project_4/project_crud/app_crud/forms.py
from django import forms

from app_crud.models import Person


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

        # Add widgets for specific fields
        widgets = {
            'gender': forms.RadioSelect,
            'hobbies': forms.CheckboxSelectMultiple,
            'country': forms.Select
        }

project_4/project_crud/app_crud/views.py
from django.shortcuts import render, get_object_or_404, redirect

from app_crud.forms import PersonForm
from app_crud.models import Person


# Create your views here.
def person_list(request):
    persons = Person.objects.all()
    return render(request, 'person_list.html', {'people': persons})


def person_detail(request, pk):
    person = get_object_or_404(Person, pk=pk)
    return render(request, 'person_detail.html', {'person': person})


def person_new(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            person = form.save()
            return redirect('person_detail', pk=person.pk)
    else:
        form = PersonForm()
    return render(request, 'person_edit.html', {'form': form})


def person_edit(request, pk):
    person = get_object_or_404(Person, pk=pk)
    if request.method == 'POST':
        form = PersonForm(request.POST, instance=person)
        if form.is_valid():
            person = form.save()
            return redirect('person_detail', pk=person.pk)
    else:
        form = PersonForm(instance=person)
    return render(request, 'person_edit.html', {'form': form})


def person_delete(request, pk):
    person = get_object_or_404(Person, pk=pk)
    person.delete()
    return redirect('person_list')

project_4/project_crud/app_crud/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Project Crud {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="#">Logo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/person/new">Add New</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">Person List</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid mt-3">

    <div class="row">
        <div class="col-2">
            <div class="offcanvas offcanvas-start" id="demo">
                <div class="offcanvas-header">
                    <h1 class="offcanvas-title">Heading</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
                </div>
                <div class="offcanvas-body">
                 <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/person/new">Add New</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/">List</a>
                </li>
            </ul>
                </div>
            </div>


        </div>
        <div class="col-10">

            <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#demo">
                Open Offcanvas Sidebar
            </button>
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>
<div class="container-fluid bg-black">
    <div class="container m-5">
        <div class="row text-white">
            <div class="col-6">
                <p>&copy; All rights reserved. </p>
            </div>
            <div class="col-6">
                <p>Developed By- The ABC Limited</p>
            </div>
        </div>
    </div>
</div>
</body>
</html>

project_4/project_crud/app_crud/templates/person_detail.html
{% extends 'base.html' %}

{% block title %} Person Detail {% endblock %}

{% block content %}


    <h2>Person Detail</h2>
    <table class="table">
        <tr>
            <th>ID</th>
            <td>{{ person.id }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ person.name }}</td>
        </tr>
        <tr>
            <th>Gender</th>
            <td>{{ person.get_gender_display }}</td>
        </tr>
        <tr>
            <th>Hobbies</th>
            <td>{% if person.hobbies.all %} {{ person.hobbies.all | join:", " }}{% else %}None{% endif %}</td>
        </tr>
        <tr>
            <th>Country</th>
            <td>{{ person.get_country_display }}</td>
        </tr>
        <tr>
            <th>Comments</th>
            <td>{{ person.comments }}</td>
        </tr>
    </table>
  <a href="{% url 'person_edit' pk=person.pk %}">Edit</a>
    <a href="{% url 'person_list' %}">Back To List</a>
{% endblock %}

project_4/project_crud/app_crud/templates/person_edit.html
{% extends 'base.html' %}
{% block title %} Person Edit {% endblock %}
{% block content %}



    <h1>New /Edit Person </h1>
    <form method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Save</button>
    </form>
<a href="{% url 'person_list' %}">Back To List</a>
{% endblock %}

project_4/project_crud/app_crud/templates/person_list.html
{% extends 'base.html' %}

{% block title %} Person List {% endblock %}


{% block content %}

<a href="{% url 'person_new' %}">Add New</a>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Gender</th>
            <th>Hobbies</th>
            <th>Country</th>
            <th>Date Of Birth</th>
            <th>Comments</th>
            <th>Action</th>
        </tr>
        {% for person in people %}
            <tr>
                <td>{{ person.name }}</td>
                <td>{{ person.get_gender_display }}</td>
                <td>{% if person.hobbies.all %} {{ person.hobbies.all | join:", " }}{% else %}None{% endif %}</td>
                <td>{{ person.get_country_display }}</td>
                <td>{{ person.birth_date }}</td>
                <td>{{ person.comments }}</td>
                <td>
                    <a href="{% url 'person_detail' pk=person.pk %}">View Detail</a>
                    <a href="{% url 'person_edit' pk=person.pk %}">Edit</a>
                    <a href="{% url 'person_delete' pk=person.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}